version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: streamService
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - '5433:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
